import {
	and,
	count,
	eq,
	type InferInsertModel,
	ilike,
	or,
	type SQL,
} from "drizzle-orm";
import {
	getPermissionsForRole,
	ROLE_DASHBOARD_MAP,
	ROLES,
	type Role,
} from "./permissions";
import { hashPassword } from "../utils/password-hasher"; // Assuming a utility file for secure hashing
import { db } from "./db";
import { roles, securityAuditLog, staff, user, userRoles, account, session } from "./schema";

// =============================================================================
// TYPES
// =============================================================================

// Define the shape of the data needed to create a new user (from Super Admin UI)
export interface NewUserParams {
	fullName: string;
	employeeId: string;
	email: string;
	roleName: Role;
	branchId: number;
	warehouseId?: number;
	initialPassword?: string;
	forcePasswordChange: boolean;
	actorId: string; // The ID of the Super Admin performing the action
}

// Define the possible statuses for the user account (from auth-schema.ts)
export type UserStatus = InferInsertModel<typeof user>["status"];

// =============================================================================
// REPOSITORY
// =============================================================================

export class UserManagementRepository {
	/**
	 * Creates a new user account, an associated staff record, and assigns the initial role.
	 * This operation must be transactional (Requirement 2, 15).
	 */
	async createUserWithStaffAndRole(params: NewUserParams) {
		const {
			fullName,
			employeeId,
			email,
			roleName,
			branchId,
			warehouseId,
			initialPassword,
			forcePasswordChange,
			actorId,
		} = params;

		// --- PRE-CHECKS (Requirement 22) ---------------------------------------------
		// Note: Checking for duplicates before the transaction simplifies error handling.

		// Check for duplicate employee ID in the staff table
		const [existingStaffCode] = await db
			.select({ staff_code: staff.staff_code })
			.from(staff)
			.where(eq(staff.staff_code, employeeId));

		if (existingStaffCode) {
			throw new Error(`Duplicate employee ID: ${employeeId}`);
		}

		// Check for duplicate email in staff and user tables
		const [existingStaffEmail] = await db
			.select({ email: staff.email })
			.from(staff)
			.where(eq(staff.email, email));

		if (existingStaffEmail) {
			throw new Error(`Duplicate email found in staff records: ${email}`);
		}

		const [existingUserEmail] = await db
			.select({ email: user.email })
			.from(user)
			.where(eq(user.email, email));

		if (existingUserEmail) {
			throw new Error(`Duplicate email found in user accounts: ${email}`);
		}

		// Enforce STRICT single Super Admin constraint: Only ONE Super Admin can exist in the entire system.
		if (roleName === "super_admin") {
			const existingSuperAdmins = await db
				.select()
				.from(userRoles)
				.leftJoin(roles, eq(userRoles.role_id, roles.id))
				.where(eq(roles.name, "super_admin"));

			if (existingSuperAdmins.length > 0) {
				throw new Error("Strict System Limit: There can strictly only be ONE Super Admin in the ERP system.");
			}
		}

		// --- END PRE-CHECKS ----------------------------------------------------------

		// 1. Validate if role exists
		if (!ROLES.includes(roleName)) {
			throw new Error(`Invalid role: ${roleName}`);
		}

		// 2. Hash the password securely (Requirement 6)
		const hashedPassword = await hashPassword(
			initialPassword || crypto.randomUUID(),
		);

		// 3. Perform the transactional insert
		return await db.transaction(async (tx) => {
			// Find the role ID
			const [roleRecord] = await tx
				.select()
				.from(roles)
				.where(eq(roles.name, roleName));

			if (!roleRecord) {
				tx.rollback();
				throw new Error(`Role not found: ${roleName}`);
			}

			// A. Create the Staff (Employee) record first (Requirement 15)
			const [newStaff] = await tx
				.insert(staff)
				.values({
					name: fullName,
					staff_code: employeeId,
					email: email,
					branch_id: branchId,
					role: roleName,
					department: "Default",
					join_date: new Date(),
					salary: "0.00",
				})
				.returning({ id: staff.id });

			if (!newStaff) {
				tx.rollback();
				throw new Error("Failed to create staff record.");
			}

			// B. Create the User (Auth) record (Requirement 2)
			// Note: The user ID will be generated by the `better-auth` integration logic (UUID/ULID),
			// but for Drizzle's direct insertion, we generate a UUID for the user ID (PK is text).
			const newUserId = crypto.randomUUID(); // Placeholder for the actual auth system ID
			await tx.insert(user).values({
				id: newUserId,
				name: fullName,
				email: email,
				emailVerified: true,
				staff_id: newStaff.id,
				branch_id: branchId,
				warehouse_id: warehouseId,
				status: "ACTIVE", // Default to active, or PENDING if temp password is used
				force_password_change: forcePasswordChange,
				password_changed_at: forcePasswordChange ? undefined : new Date(),
			});

			// C. Insert credentials record (assuming better-auth stores credentials in the `account` table or similar)
			// Note: The actual credentials insertion logic will depend on the `better-auth` implementation.
			// Assuming it is handled outside, or needs to be inserted into a separate `account` table as per auth-schema.ts
			// For now, we will add a placeholder for password storage, which is usually in the `account` table or an internal `password` table.
			// Given the `account` table in `auth-schema.ts` has a `password` field, we'll assume a direct entry there is necessary.
			// NOTE: The password should be stored in a linked table or a dedicated `account` table in a real system.
			// Since `auth-schema.ts` showed an `account` table with a `password` field, we link the password there.
			// This is a simplification, but necessary without knowing the exact better-auth implementation detail.
			// The `account` table in auth-schema.ts has a `userId`, `providerId`, and a `password` text field.
			// We will insert a local provider account.
			await tx.insert(account).values({
				id: crypto.randomUUID(),
				accountId: email, // Use email as account ID for local provider
				providerId: "evaluna_local",
				userId: newUserId,
				password: hashedPassword,
			});

			// D. Assign the Role (Requirement 2)
			await tx.insert(userRoles).values({
				user_id: newUserId,
				role_id: roleRecord.id,
			});

			// E. Audit Log (Requirement 16)
			await tx.insert(securityAuditLog).values({
				actor_id: actorId,
				target_user_id: newUserId,
				action: "USER_CREATED",
				description: `User ${fullName} created with role ${roleName}`,
				reason: "Super Admin action",
			});

			return { userId: newUserId, staffId: newStaff.id, role: roleName };
		});
	}

	/**
	 * Updates the user's status (ACTIVE, INACTIVE, LOCKED, SUSPENDED) and logs the action (Requirement 7, 16).
	 */
	async updateUserStatus(
		targetUserId: string,
		newStatus: UserStatus,
		reason: string,
		actorId: string,
	) {
		return await db.transaction(async (tx) => {
			const [existingUser] = await tx
				.select()
				.from(user)
				.where(eq(user.id, targetUserId))
				.limit(1);

			if (!existingUser) {
				tx.rollback();
				throw new Error("Target user not found.");
			}

			// 1. Update the user status
			await tx
				.update(user)
				.set({
					status: newStatus,
					locked_until:
						newStatus === "LOCKED" ? new Date(Date.now() + 86400000) : null, // Lock for 24 hours if locked
					updatedAt: new Date(),
				})
				.where(eq(user.id, targetUserId));

			// 2. If deactivated or locked, revoke all active sessions (Requirement 18)
			if (
				newStatus === "INACTIVE" ||
				newStatus === "LOCKED" ||
				newStatus === "SUSPENDED"
			) {
				await tx.delete(session).where(eq(session.userId, targetUserId));
				// Log session revocation (part of the larger action)
				await tx.insert(securityAuditLog).values({
					actor_id: actorId,
					target_user_id: targetUserId,
					action: "SESSION_REVOKED",
					description: `Sessions revoked due to status change to ${newStatus}`,
					reason: reason,
				});
			}

			// 3. Audit Log
			await tx.insert(securityAuditLog).values({
				actor_id: actorId,
				target_user_id: targetUserId,
				action: `USER_STATUS_CHANGE_${newStatus}`,
				description: `User status changed from ${existingUser.status} to ${newStatus}`,
				reason: reason,
				previous_value: JSON.stringify({ status: existingUser.status }),
				new_value: JSON.stringify({ status: newStatus }),
			});

			return { success: true };
		});
	}

	/**
	 * Handles password reset or force password change flag update (Requirement 6).
	 */
	async updateUserCredentials(
		targetUserId: string,
		newPassword?: string,
		forceChange?: boolean,
		actorId?: string,
	) {
		const hashedPassword = newPassword
			? await hashPassword(newPassword)
			: undefined;

		return await db.transaction(async (tx) => {
			// 1. Update password hash if provided (assuming local provider)
			if (hashedPassword) {
				const [accountRecord] = await tx
					.select()
					.from(account)
					.where(
						and(
							eq(account.userId, targetUserId),
							eq(account.providerId, "evaluna_local"),
						),
					)
					.limit(1);

				if (!accountRecord) {
					tx.rollback();
					throw new Error("Local account not found for user.");
				}

				await tx
					.update(account)
					.set({ password: hashedPassword })
					.where(eq(account.id, accountRecord.id));

				// Audit log for password reset (Requirement 16)
				if (actorId) {
					await tx.insert(securityAuditLog).values({
						actor_id: actorId,
						target_user_id: targetUserId,
						action: "PASSWORD_RESET",
						description: "Password reset by Super Admin",
					});
				}
			}

			// 2. Update force password change flag and timestamp
			if (forceChange !== undefined) {
				await tx
					.update(user)
					.set({
						force_password_change: forceChange,
						password_changed_at: new Date(),
						updatedAt: new Date(),
					})
					.where(eq(user.id, targetUserId));

				// Audit log for force password change (Requirement 16)
				if (actorId) {
					await tx.insert(securityAuditLog).values({
						actor_id: actorId,
						target_user_id: targetUserId,
						action: "FORCE_PASSWORD_CHANGE_TOGGLED",
						description: `Force password change set to ${forceChange}`,
					});
				}
			}

			return { success: true };
		});
	}

	/**
	 * Updates the user's role and scopes (branch/warehouse) (Requirement 14).
	 * Requires permissions check to prevent privilege escalation.
	 */
	async changeUserRoleAndScope(
		targetUserId: string,
		newRoleName: Role,
		newBranchId: number,
		newWarehouseId: number | undefined,
		actorId: string,
	) {
		// IMPORTANT: Permission check for change_role is assumed to be handled by the caller (API layer)
		// by checking `users.change_role` permission for the actorId. The repository assumes
		// the actor is authorized, but we check if the new role is valid.
		if (!ROLES.includes(newRoleName)) {
			throw new Error(`Invalid role: ${newRoleName}`);
		}

		// Enforce STRICT single Super Admin constraint during role updates
		if (newRoleName === "super_admin") {
			const existingSuperAdmins = await db
				.select()
				.from(userRoles)
				.leftJoin(roles, eq(userRoles.role_id, roles.id))
				.where(eq(roles.name, "super_admin"));

			const otherSuperAdminExists = existingSuperAdmins.some((row) => row.user_roles.user_id !== targetUserId);
			if (otherSuperAdminExists) {
				throw new Error("Strict System Limit: There can strictly only be ONE Super Admin in the ERP system.");
			}
		}

		return await db.transaction(async (tx) => {
			const [existingUser] = await tx
				.select({ id: user.id, staffId: user.staff_id, roleName: roles.name })
				.from(user)
				.where(eq(user.id, targetUserId))
				.leftJoin(userRoles, eq(user.id, userRoles.user_id))
				.leftJoin(roles, eq(userRoles.role_id, roles.id))
				.limit(1);

			if (!existingUser) {
				tx.rollback();
				throw new Error("Target user not found.");
			}

			const oldRole = existingUser.roleName || "customer";

			// 1. Get new role ID
			const [newRoleRecord] = await tx
				.select()
				.from(roles)
				.where(eq(roles.name, newRoleName));

			if (!newRoleRecord) {
				tx.rollback();
				throw new Error(`Role not found: ${newRoleName}`);
			}

			// 2. Update userRoles table (Delete old role, insert new one)
			await tx.delete(userRoles).where(eq(userRoles.user_id, targetUserId));

			await tx.insert(userRoles).values({
				user_id: targetUserId,
				role_id: newRoleRecord.id,
			});

			// 3. Update staff record's legacy role field and name (Requirement 15 consistency)
			if (existingUser.staffId) {
				await tx
					.update(staff)
					.set({
						role: newRoleName,
					})
					.where(eq(staff.id, existingUser.staffId));
			}

			// 4. Update user account scope (branch/warehouse)
			await tx
				.update(user)
				.set({
					branch_id: newBranchId,
					warehouse_id: newWarehouseId,
					updatedAt: new Date(),
				})
				.where(eq(user.id, targetUserId));

			// 5. Revoke all active sessions (Requirement 14, 18)
			await tx.delete(session).where(eq(session.userId, targetUserId));

			// 6. Audit Log (Requirement 16)
			await tx.insert(securityAuditLog).values({
				actor_id: actorId,
				target_user_id: targetUserId,
				action: "ROLE_CHANGED",
				description: `Role changed from ${oldRole} to ${newRoleName}. Scope updated. Sessions revoked.`,
				previous_value: JSON.stringify({ role: oldRole }),
				new_value: JSON.stringify({
					role: newRoleName,
					branchId: newBranchId,
					warehouseId: newWarehouseId,
				}),
			});

			return { success: true };
		});
	}

	/**
	 * Revokes all active sessions for a user (Requirement 18).
	 */
	async revokeUserSessions(
		targetUserId: string,
		reason: string,
		actorId: string,
	) {
		return await db.transaction(async (tx) => {
			// 1. Revoke sessions
			await tx.delete(session).where(eq(session.userId, targetUserId));

			// 2. Audit Log (Requirement 16)
			await tx.insert(securityAuditLog).values({
				actor_id: actorId,
				target_user_id: targetUserId,
				action: "SESSION_REVOKED_MANUAL",
				description: "All active sessions manually revoked.",
				reason: reason,
			});

			return { success: true };
		});
	}

	/**
	 * Retrieves the full security profile for a user during login/session validation.
	 * This is the heart of the AuthZ logic (Requirement 5).
	 */
	async getSecurityProfileByUserId(targetUserId: string) {
		const [userRecord] = await db
			.select({
				id: user.id,
				name: user.name,
				email: user.email,
				status: user.status,
				forcePasswordChange: user.force_password_change,
				staffId: user.staff_id,
				branchId: user.branch_id,
				warehouseId: user.warehouse_id,
				isSuperAdmin: user.is_superadmin,
				lockedUntil: user.locked_until, // ADDED: Required for login check
			})
			.from(user)
			.where(eq(user.id, targetUserId))
			.limit(1);

		if (!userRecord) return null;

		// 1. Get Roles
		const userRoleRecords = await db
			.select({
				roleName: roles.name,
			})
			.from(userRoles)
			.innerJoin(roles, eq(userRoles.role_id, roles.id))
			.where(eq(userRoles.user_id, targetUserId));

		// Assuming single role per user for simplicity, prioritizing the first one found.
		// A multi-role implementation would require further logic (e.g., permission merging).
		const primaryRoleName = userRecord.isSuperAdmin
			? "super_admin"
			: (userRoleRecords[0]?.roleName as Role) || "customer";

		// 2. Get Permissions (Derived from role)
		const permissions = getPermissionsForRole(primaryRoleName);

		// 3. Resolve Dashboard Route
		const canonicalDashboard = ROLE_DASHBOARD_MAP[primaryRoleName];

		return {
			...userRecord,
			role: primaryRoleName,
			permissions: permissions,
			canonicalDashboard: canonicalDashboard,
			scope: {
				branchId: userRecord.branchId,
				warehouseId: userRecord.warehouseId,
			},
		};
	}

	/**
	 * Retrieves all details for a single user, including staff record and role.
	 */
	async getUserById(userId: string) {
		const usersData = await db
			.select({
				id: user.id,
				name: user.name,
				email: user.email,
				status: user.status,
				isSuperAdmin: user.is_superadmin,
				lastActiveAt: user.last_active_at,
				createdAt: user.createdAt,
				passwordChangedAt: user.password_changed_at,
				forcePasswordChange: user.force_password_change,
				staffId: staff.id,
				staffCode: staff.staff_code,
				roleName: roles.name,
				branchId: user.branch_id,
				warehouseId: user.warehouse_id,
			})
			.from(user)
			.where(eq(user.id, userId))
			.leftJoin(staff, eq(user.staff_id, staff.id))
			.leftJoin(userRoles, eq(user.id, userRoles.user_id))
			.leftJoin(roles, eq(userRoles.role_id, roles.id))
			.limit(1);

		const userRecord = usersData[0];

		if (!userRecord) return null;

		const primaryRoleName = userRecord.isSuperAdmin
			? "super_admin"
			: (userRecord.roleName as Role) || "customer";

		const permissions = getPermissionsForRole(primaryRoleName);

		return {
			...userRecord,
			role: primaryRoleName,
			permissions: permissions,
		};
	}

	/**
	 * Lists users with filtering and pagination support (Requirement 19).
	 */
	async listUsers(
		page = 1,
		limit = 10,
		filters: {
			roleName?: Role;
			status?: UserStatus;
			branchId?: number;
			warehouseId?: number;
			search?: string;
		} = {},
	) {
		const offset = (page - 1) * limit;

		const whereClauses: (SQL<unknown> | undefined)[] = [];

		if (filters.status) {
			whereClauses.push(eq(user.status, filters.status));
		}
		if (filters.branchId) {
			whereClauses.push(eq(user.branch_id, filters.branchId));
		}
		if (filters.warehouseId) {
			whereClauses.push(eq(user.warehouse_id, filters.warehouseId));
		}
		if (filters.search) {
			const searchPattern = `%${filters.search.toLowerCase()}%`;
			whereClauses.push(
				or(
					ilike(user.name, searchPattern),
					ilike(user.email, searchPattern),
					ilike(staff.staff_code, searchPattern), // Added search by Employee ID
				),
			);
		}

		// Base query with joins
		const userQuery = db
			.select({
				id: user.id,
				name: user.name,
				email: user.email,
				status: user.status,
				branchId: user.branch_id,
				warehouseId: user.warehouse_id,
				isSuperAdmin: user.is_superadmin,
				lastActiveAt: user.last_active_at,
				createdAt: user.createdAt,
				staffId: staff.id,
				staffCode: staff.staff_code,
				roleName: roles.name,
			})
			.from(user)
			.leftJoin(staff, eq(user.staff_id, staff.id))
			.leftJoin(userRoles, eq(user.id, userRoles.user_id))
			.leftJoin(roles, eq(userRoles.role_id, roles.id));

		const usersData = await userQuery
			.where(and(...(whereClauses.filter(Boolean) as SQL<unknown>[])))
			.limit(limit)
			.offset(offset);

		// NOTE: Role filtering is complex due to the left join, we'll implement it in application logic for simplicity.
		const filteredUsers = filters.roleName
			? usersData.filter(
					(u) =>
						u.roleName === filters.roleName ||
						(u.isSuperAdmin && filters.roleName === "super_admin"),
				)
			: usersData;

		// Total count query
		const [totalCountResult] = await db
			.select({ count: count() })
			.from(user)
			.where(and(...(whereClauses.filter(Boolean) as SQL<unknown>[]))); // Re-use where clauses for count

		const totalUsers = totalCountResult?.count ?? 0;

		return {
			users: filteredUsers.map((u) => ({
				...u,
				// Resolve final role for display
				role: u.isSuperAdmin ? "super_admin" : (u.roleName as Role),
			})),
			pagination: {
				total: totalUsers,
				page,
				limit,
				totalPages: Math.ceil(totalUsers / limit),
			},
		};
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// PLACEHOLDERS / UTILITIES
// ─────────────────────────────────────────────────────────────────────────────

export const UserManagement = new UserManagementRepository();
